In [1]:
import polars as pl

In [5]:
file = pl.read_parquet("./profile/grids/ema_parquets/lp0000_20000_0350_0020.parquet")

In [7]:
file

shape: (260_001, 15)
┌────────────┬──────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ wavelength ┆ I1       ┆ I2       ┆ I3       ┆ … ┆ cont4    ┆ cont5    ┆ cont6    ┆ cont7    │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ f64        ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞════════════╪══════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 3800.0     ┆ 0.000871 ┆ 0.000858 ┆ 0.000843 ┆ … ┆ 0.001252 ┆ 0.00119  ┆ 0.001104 ┆ 0.000947 │
│ 3800.02    ┆ 0.000874 ┆ 0.00086  ┆ 0.000845 ┆ … ┆ 0.001252 ┆ 0.00119  ┆ 0.001104 ┆ 0.000947 │
│ 3800.04    ┆ 0.000876 ┆ 0.000863 ┆ 0.000847 ┆ … ┆ 0.001252 ┆ 0.00119  ┆ 0.001104 ┆ 0.000947 │
│ 3800.06    ┆ 0.000879 ┆ 0.000865 ┆ 0.00085  ┆ … ┆ 0.001252 ┆ 0.00119  ┆ 0.001104 ┆ 0.000947 │
│ 3800.08    ┆ 0.000881 ┆ 0.000868 ┆ 0.000852 ┆ … ┆ 0.001252 ┆ 0.00119  ┆ 0.001104 ┆ 0.000947 │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ 8999.92    ┆ 0.00032  ┆ 0.000318 ┆ 0.000314 ┆ … ┆ 0.000351 ┆ 0.000343 ┆ 0.000331 ┆ 0.000309 │
│ 8999.94    ┆ 0.000321 ┆ 0.000318 ┆ 0.000315 ┆ … ┆ 0.000351 ┆ 0.000343 ┆ 0.000331 ┆ 0.000309 │
│ 8999.96    ┆ 0.000322 ┆ 0.000319 ┆ 0.000316 ┆ … ┆ 0.000351 ┆ 0.000343 ┆ 0.000331 ┆ 0.000309 │
│ 8999.98    ┆ 0.000323 ┆ 0.00032  ┆ 0.000317 ┆ … ┆ 0.000351 ┆ 0.000343 ┆ 0.000331 ┆ 0.000309 │
│ 9000.0     ┆ 0.000324 ┆ 0.000321 ┆ 0.000318 ┆ … ┆ 0.000351 ┆ 0.000343 ┆ 0.000331 ┆ 0.000309 │
└────────────┴──────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [8]:
file2 = pl.read_parquet("./profile/deformed_star.parquet")

In [12]:
file2.sort("area")

shape: (6_144, 8)
┌──────────┬──────────┬──────┬────────────┬──────────────┬─────────────┬──────────┬───────────┐
│ coord1   ┆ coord2   ┆ time ┆ velocity   ┆ temperature  ┆ log gravity ┆ coschi   ┆ area      │
│ ---      ┆ ---      ┆ ---  ┆ ---        ┆ ---          ┆ ---         ┆ ---      ┆ ---       │
│ f64      ┆ f64      ┆ f64  ┆ f64        ┆ f64          ┆ f64         ┆ f64      ┆ f64       │
╞══════════╪══════════╪══════╪════════════╪══════════════╪═════════════╪══════════╪═══════════╡
│ 1.094677 ┆ 4.196971 ┆ 0.0  ┆ -10.936343 ┆ 22741.373295 ┆ 3.766728    ┆ 0.000469 ┆ 4.7760e-7 │
│ 1.094677 ┆ 2.086214 ┆ 0.0  ┆ 10.936343  ┆ 22741.373295 ┆ 3.766728    ┆ 0.000469 ┆ 4.7760e-7 │
│ 2.356088 ┆ 5.995206 ┆ 0.0  ┆ -2.840457  ┆ 22507.722217 ┆ 3.742366    ┆ 0.000643 ┆ 6.6192e-7 │
│ 2.356088 ┆ 0.287979 ┆ 0.0  ┆ 2.840457   ┆ 22507.722217 ┆ 3.742366    ┆ 0.000643 ┆ 6.6192e-7 │
│ 0.998378 ┆ 4.049709 ┆ 0.0  ┆ -9.371693  ┆ 22674.191349 ┆ 3.759862    ┆ 0.001023 ┆ 0.000001  │
│ …        ┆ …        ┆ …    ┆ …          ┆ …            ┆ …           ┆ …        ┆ …         │
│ 0.757964 ┆ 6.256103 ┆ 0.0  ┆ -0.263264  ┆ 22485.530439 ┆ 3.73998     ┆ 0.9998   ┆ 0.00103   │
│ 0.703326 ┆ 0.029089 ┆ 0.0  ┆ 0.266025   ┆ 22441.76759  ┆ 3.735234    ┆ 0.997954 ┆ 0.001031  │
│ 0.703326 ┆ 6.254096 ┆ 0.0  ┆ -0.266025  ┆ 22441.76759  ┆ 3.735234    ┆ 0.997954 ┆ 0.001031  │
│ 0.730574 ┆ 0.02805  ┆ 0.0  ┆ 0.264673   ┆ 22463.526086 ┆ 3.7376      ┆ 0.999253 ┆ 0.001031  │
│ 0.730574 ┆ 6.255135 ┆ 0.0  ┆ -0.264673  ┆ 22463.526086 ┆ 3.7376      ┆ 0.999253 ┆ 0.001031  │
└──────────┴──────────┴──────┴────────────┴──────────────┴─────────────┴──────────┴───────────┘

In [14]:
file3 = pl.read_parquet("./profile/undeformed_tp.parquet")

In [15]:
file3

shape: (384, 8)
┌──────────┬──────────┬──────┬───────────┬──────────────┬─────────────┬──────────┬──────────┐
│ coord1   ┆ coord2   ┆ time ┆ velocity  ┆ temperature  ┆ log gravity ┆ coschi   ┆ area     │
│ ---      ┆ ---      ┆ ---  ┆ ---       ┆ ---          ┆ ---         ┆ ---      ┆ ---      │
│ f64      ┆ f64      ┆ f64  ┆ f64       ┆ f64          ┆ f64         ┆ f64      ┆ f64      │
╞══════════╪══════════╪══════╪═══════════╪══════════════╪═════════════╪══════════╪══════════╡
│ 1.487366 ┆ 0.785398 ┆ 0.01 ┆ -0.318524 ┆ 22631.325349 ┆ 3.755548    ┆ 0.555255 ┆ 0.009088 │
│ 1.403348 ┆ 0.883573 ┆ 0.01 ┆ -0.636567 ┆ 22624.338163 ┆ 3.754557    ┆ 0.55867  ┆ 0.009146 │
│ 1.403348 ┆ 0.687223 ┆ 0.01 ┆ -0.391297 ┆ 22619.694444 ┆ 3.754817    ┆ 0.655312 ┆ 0.010728 │
│ 1.318116 ┆ 0.785398 ┆ 0.01 ┆ -0.700828 ┆ 22614.984609 ┆ 3.754035    ┆ 0.659974 ┆ 0.010806 │
│ 1.318116 ┆ 0.981748 ┆ 0.01 ┆ -0.93218  ┆ 22621.721102 ┆ 3.753735    ┆ 0.556171 ┆ 0.009106 │
│ …        ┆ …        ┆ …    ┆ …         ┆ …            ┆ …           ┆ …        ┆ …        │
│ 1.823477 ┆ 5.301438 ┆ 0.01 ┆ -0.481899 ┆ 22667.986534 ┆ 3.754301    ┆ 0.203799 ┆ 0.003334 │
│ 1.823477 ┆ 5.497787 ┆ 0.01 ┆ -0.753662 ┆ 22673.869336 ┆ 3.754755    ┆ 0.30723  ┆ 0.005026 │
│ 1.738244 ┆ 5.595962 ┆ 0.01 ┆ -0.58102  ┆ 22667.542456 ┆ 3.755401    ┆ 0.420449 ┆ 0.006878 │
│ 1.738244 ┆ 5.399612 ┆ 0.01 ┆ -0.419865 ┆ 22663.606012 ┆ 3.755037    ┆ 0.324231 ┆ 0.005305 │
│ 1.654226 ┆ 5.497787 ┆ 0.01 ┆ -0.10146  ┆ 22654.592601 ┆ 3.755832    ┆ 0.438657 ┆ 0.007177 │
└──────────┴──────────┴──────┴───────────┴──────────────┴─────────────┴──────────┴──────────┘

In [48]:
file4 = pl.read_parquet("./profile/undeformed_star.parquet")

In [49]:
file4.filter(pl.col("time")>0.01)

shape: (483, 8)
┌──────────┬──────────┬──────┬────────────┬──────────────┬─────────────┬──────────┬──────────┐
│ coord1   ┆ coord2   ┆ time ┆ velocity   ┆ temperature  ┆ log gravity ┆ coschi   ┆ area     │
│ ---      ┆ ---      ┆ ---  ┆ ---        ┆ ---          ┆ ---         ┆ ---      ┆ ---      │
│ f64      ┆ f64      ┆ f64  ┆ f64        ┆ f64          ┆ f64         ┆ f64      ┆ f64      │
╞══════════╪══════════╪══════╪════════════╪══════════════╪═════════════╪══════════╪══════════╡
│ 1.799047 ┆ 3.252639 ┆ 0.02 ┆ 25.916107  ┆ 22777.391508 ┆ 3.730201    ┆ 0.820505 ┆ 0.029601 │
│ 1.609886 ┆ 3.359543 ┆ 0.02 ┆ 25.258291  ┆ 22792.325986 ┆ 3.727216    ┆ 0.724043 ┆ 0.026101 │
│ 1.422115 ┆ 3.250995 ┆ 0.02 ┆ 23.506639  ┆ 22787.78071  ┆ 3.728127    ┆ 0.627916 ┆ 0.022643 │
│ 1.422116 ┆ 3.032122 ┆ 0.02 ┆ 25.852825  ┆ 22787.78071  ┆ 3.728127    ┆ 0.627944 ┆ 0.02264  │
│ 1.609886 ┆ 2.923602 ┆ 0.02 ┆ 29.950662  ┆ 22792.325986 ┆ 3.727216    ┆ 0.724029 ┆ 0.026104 │
│ …        ┆ …        ┆ …    ┆ …          ┆ …            ┆ …           ┆ …        ┆ …        │
│ 1.49957  ┆ 4.326695 ┆ 0.03 ┆ -4.177579  ┆ 22361.964233 ┆ 3.730384    ┆ 0.178488 ┆ 0.003938 │
│ 1.61692  ┆ 4.219553 ┆ 0.03 ┆ 4.500325   ┆ 22362.060323 ┆ 3.73039     ┆ 0.388115 ┆ 0.010713 │
│ 1.52063  ┆ 4.272083 ┆ 0.03 ┆ 1.519937   ┆ 22355.678126 ┆ 3.729778    ┆ 0.316259 ┆ 0.007295 │
│ 1.344412 ┆ 4.376649 ┆ 0.03 ┆ -6.484691  ┆ 22392.113387 ┆ 3.733265    ┆ 0.096529 ┆ 0.002018 │
│ 1.326182 ┆ 4.48783  ┆ 0.03 ┆ -10.638057 ┆ 22413.12278  ┆ 3.73527     ┆ 0.002994 ┆ 0.000057 │
└──────────┴──────────┴──────┴────────────┴──────────────┴─────────────┴──────────┴──────────┘